### PR TITLE
Add: Double reverse log

### LINKED ISSUE #18: New transformation: reverse log (and or other reverse transformations)
I am aware that one can [feed custom functions to `bestNormalize`](https://petersonr.github.io/bestNormalize/articles/customization.html). However, I am wondering if it would be worth adding this particular transformation to the package.

A colleague has observed that he obtains a better transformation (i.e., more normally distributed variable) when reversing scores of his variable, and then using a log (and eventually reversing scores once again), than the default selected choice with `bestNormalize`.

A couple of questions then:
- Is this expected/does it make any sense?
- Would it be worthwhile to implement it in the package?
- Would you have the time to implement it/would you rather me submitting a PR?
- If we are to include the procedure to reverse scores before using the log transform, should a similar procedure be applied to all other methods (if it changes anything; except maybe Box-Cox and Yeo-Jonhson)? That would almost double the number of transformations available.

### PR DESCRIPTION
**Pull request by rempsyc**
Closes #18 

---

Reprex:

``` r
devtools::load_all("D:/github/forks/bestNormalize")
#> ℹ Loading bestNormalize

# Prepare left-skewed data
set.seed(42)
x <- rgamma(1000, 1, 2)
x <- nice_reverse(x, max = 5, min = 4)
hist(x)
```

``` r

# Transform
double_reverse_log_obj <- double_reverse_log(x)
double_reverse_log_obj
#> Standardized double reversed Log_b(x + a) Transformation with 1000 nonmissing obs.:
#>  Relevant statistics:
#>  - a = 0 
#>  - b = 10 
#>  - mean (before standardization) = 0.9210104 
#>  - sd (before standardization) = 0.03085899
p <- predict(double_reverse_log_obj)
hist(p)
```

``` r

# Back transform...
x2 <- predict(double_reverse_log_obj, newdata = p, inverse = TRUE)

all.equal(x, x2)
#> [1] TRUE

# Validate it works with standardized = FALSE
double_reverse_log_obj2 <- double_reverse_log(x, standardize = FALSE)
double_reverse_log_obj2
#> Non-Standardized double reversed Log_b(x + a) Transformation with 1000 nonmissing obs.:
#>  Relevant statistics:
#>  - a = 0 
#>  - b = 10 
#>  - mean (before standardization) = 0.9210104 
#>  - sd (before standardization) = 0.03085899
p2 <- predict(double_reverse_log_obj2)
hist(p2)
```

``` r

# Back transform...
x3 <- predict(double_reverse_log_obj2, newdata = p2, inverse = TRUE)

all.equal(x, x3)
#> [1] TRUE
```

<sup>Created on 2022-12-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by rempsyc** [comment]
A few observations.

1. If I understand correctly, even though the transformation has already been done in the `log_x_obj`, when using `predict()`, the original data is extracted from the `log_x_obj` object again, and then the transformation is applied to it? Why not just pull the already-transformed data from the `log_x_obj`? Alternatively, why calculate it in the first part and not just in `predict()`? For large data sets I suppose performing the transformation only once would double the function's performance.

2. I was able to fix a few failing tests however there remains two I believe. The first is in the `test_bn_parallel` test file, line 34: there is an issue with the `cluster` argument when `loo = TRUE` (leave one out). I've looked into that code a bit but it seems a bit buried. The second failing test is about the same issue, but on line 225.

In `test_bn_custom_normstat` line 23, there seems to be an issue with negative values, so my workaround for now was to change the -1 to 1, but of course we should find a better fix if possible.

It's a start at least! :-)

**Comment by petersonR** [comment]
Thanks for your diligence on this. I believe a remaining issue is related to point 1. above. The reason to have a `log_x_obj` separately from `predict` is that the `log_x` function *trains* the transformation, and the `predict` function *applies* the transformation consistently to new (or old) data. There can be no "re-training" done in the `predict` function, or else new data will not be transformed consistently. However, by using the minimum/maximum of the new data in your `predict` function, this is re-training the transformation to the new data and therefore will be inconsistent. See example below: 

```r 
> set.seed(1)
> x1 <- 100- rgamma(100, .1)
> 
> drl_x1_obj <- double_reverse_log(x1)
> 
> all.equal(predict(drl_x1_obj, newdata = x1), predict(drl_x1_obj, x1))
[1] TRUE
> all.equal(predict(drl_x1_obj, newdata = x1[2]), predict(drl_x1_obj, x1)[2])
[1] "Mean relative difference: 0.001852533"
> # transformed value for x1[2] depends on input of newdata

> # Am I sure this will work on other transformations? 
> lx_obj <- log_x(x1)
> orn_obj <- orderNorm(x12, warn = FALSE)
> 
> all.equal(predict(lx_obj, newdata = x1[2]), predict(lx_obj, x1)[2]) # yes
[1] TRUE
> all.equal(predict(orn_obj, newdata = x1[2]), predict(orn_obj, x1)[2]) # yes
[1] TRUE
```

Basically, `predict(x[i])` should be equivalent to `predict(x)[i]` for all `i`. I think I might add this as a test for all the functions, sorry it wasn't there already. I tried to make a few small tweaks to solve the problem but created many more issues doing so, so I'm stuck. 

A second consideration pertains to the log_x `a` and `eps` parameters. These control the selection for the offset which occurs prior to the log transformation. In this case, what constant should be added to the reversed scores prior to logging? I'm not sure reversing the scores using the formula max(x) - x + min(x) is the "right" way to always reverse the scores; I think your previous version of `min = 1` makes more sense, at least for the left-skewed data on which this transformation is intended. Perhaps to be consistent we should do `min = eps`, and have `eps = 0.001` by default. See a few examples of this below. 

```r
set.seed(1)
x <- 100 - rgamma(100, .2)*4
par(mfrow = c(2,2))
hist(x)
hist(log(100-x + 1))
hist(log(100-x + .001))
hist(log(100-x + min(x)))
```
image

**Comment by rempsyc** [comment]
> The reason to have a log_x_obj separately from predict is that the log_x function trains the transformation, and the predict function applies the transformation consistently to new (or old) data. There can be no "re-training" done in the predict function, or else new data will not be transformed consistently.

Oh yep, that makes sense, my bad.

> Basically, predict(x[i]) should be equivalent to predict(x)[i] for all i.

Fixed! I am using the original data min and max now.

``` r
devtools::load_all("D:/github/forks/bestNormalize")
#> ℹ Loading bestNormalize

set.seed(1)
x1 <- 100- rgamma(100, .1)
 
drl_x1_obj <- double_reverse_log(x1)

all.equal(predict(drl_x1_obj, newdata = x1), predict(drl_x1_obj, x1))
#> [1] TRUE
all.equal(predict(drl_x1_obj, newdata = x1[2]), predict(drl_x1_obj, x1)[2])
#> [1] TRUE
# transformed value for x1[2] does not depend on input of newdata anymore
```

<sup>Created on 2022-12-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

> I'm not sure reversing the scores using the formula max(x) - x + min(x) is the "right" way to always reverse the scores; I think your previous version of min = 1 makes more sense, at least for the left-skewed data on which this transformation is intended. Perhaps to be consistent we should do min = eps, and have eps = 0.001 by default.

I was just using 1 by default because most of the Likert Scale questionnaires we use have 1 as the actual minimum. In the context of reversing negatively worded items, it makes sense to keep the original scale since we calculate an average from all items. However, I realize here it has little relevance because we reverse the scores again and so the user never quite see the reverse scoring. So we could use any value. I agree that a value = eps (.001) seems to generate the best results!

``` r
devtools::load_all("D:/github/forks/bestNormalize")
#> ℹ Loading bestNormalize

# Prepare left-skewed data
set.seed(42)
x <- rgamma(1000, 1, 2)
x <- nice_reverse(x, max = 5, min = 4)
hist(x)
```



``` r

# Transform
double_reverse_log_obj <- double_reverse_log(x)
double_reverse_log_obj
#> Standardized double reversed Log_b(x + a) Transformation with 1000 nonmissing obs.:
#>  Relevant statistics:
#>  - a = 0 
#>  - b = 10 
#>  - mean (before standardization) = -1.879383 
#>  - sd (before standardization) = 0.5505899
p <- predict(double_reverse_log_obj)
hist(p)
```



``` r

# Back transform...
x2 <- predict(double_reverse_log_obj, newdata = p, inverse = TRUE)

all.equal(x, x2)
#> [1] TRUE

# Validate it works with standardized = FALSE
double_reverse_log_obj2 <- double_reverse_log(x, standardize = FALSE)
double_reverse_log_obj2
#> Non-Standardized double reversed Log_b(x + a) Transformation with 1000 nonmissing obs.:
#>  Relevant statistics:
#>  - a = 0 
#>  - b = 10 
#>  - mean (before standardization) = -1.879383 
#>  - sd (before standardization) = 0.5505899
p2 <- predict(double_reverse_log_obj2)
hist(p2)
```



``` r

# Back transform...
x3 <- predict(double_reverse_log_obj2, newdata = p2, inverse = TRUE)

all.equal(x, x3)
#> [1] TRUE
```

<sup>Created on 2022-12-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

However, like you mention, this leads to some current examples failing because they sometimes generate NaN values when applying the transform to new data. My understanding is that this transformation creates impossible values, e.g.,

``` r
devtools::load_all("D:/github/forks/bestNormalize")
#> ℹ Loading bestNormalize

train <- iris$Petal.Width
double_reverse_log_obj <- double_reverse_log(train)

nd <- seq(0, 4, length = 100)
pred <- predict(double_reverse_log_obj, newdata = nd)
#> Warning in predict.double_reverse_log(double_reverse_log_obj, newdata = nd):
#> NaNs produced
expect_true(!any(is.na(pred)))
#> Error: !any(is.na(pred)) is not TRUE
#> 
#> `actual`:   FALSE
#> `expected`: TRUE

pred
#>   [1] -0.805994583 -0.792859141 -0.779506214 -0.765928479 -0.752118236
#>   [6] -0.738067383 -0.723767388 -0.709209255 -0.694383493 -0.679280078
#>  [11] -0.663888411 -0.648197275 -0.632194785 -0.615868335 -0.599204536
#>  [16] -0.582189152 -0.564807027 -0.547042004 -0.528876831 -0.510293067
#>  [21] -0.491270964 -0.471789343 -0.451825452 -0.431354806 -0.410351008
#>  [26] -0.388785541 -0.366627538 -0.343843517 -0.320397072 -0.296248530
#>  [31] -0.271354540 -0.245667609 -0.219135557 -0.191700875 -0.163299978
#>  [36] -0.133862317 -0.103309320 -0.071553132 -0.038495091 -0.004023877
#>  [41]  0.031986749  0.069680733  0.109223207  0.150804860  0.194647501
#>  [46]  0.241011220  0.290203741  0.342592812  0.398622909  0.458838185
#>  [51]  0.523914704  0.594706852  0.672316149  0.758196835  0.854324648
#>  [56]  0.963480471  1.089757592  1.239544521  1.423644539  1.662599274
#>  [61]  2.003667817  2.606410447          NaN          NaN          NaN
#>  [66]          NaN          NaN          NaN          NaN          NaN
#>  [71]          NaN          NaN          NaN          NaN          NaN
#>  [76]          NaN          NaN          NaN          NaN          NaN
#>  [81]          NaN          NaN          NaN          NaN          NaN
#>  [86]          NaN          NaN          NaN          NaN          NaN
#>  [91]          NaN          NaN          NaN          NaN          NaN
#>  [96]          NaN          NaN          NaN          NaN          NaN
```

<sup>Created on 2022-12-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rempsyc** [comment]
The problem is that the reverse scoring procedure creates negative scores, which the log cannot then transform. I wonder if the risk of having negative values is a problem inherent to using the min and max values from the original data instead of retraining the data set and using the min and max of the new data.

If the new data does not have the same max as the original data, we are in some cases bound to have negative values upon reversal, if we use the max from the original data.

``` r
devtools::load_all("D:/github/forks/bestNormalize")
#> ℹ Loading bestNormalize

nd <- seq(0, 4, length = 100)
max(nd)
#> [1] 4
max.petal <- max(iris$Petal.Width)
max.petal
#> [1] 2.5
nice_reverse(nd, 
             max = max.petal, 
             min = min(iris$Petal.Width)) |> 
  range()
#> [1] -1.4  2.6
nice_reverse(nd, 
             max = max.petal, 
             min = 1) |> 
  range()
#> [1] -0.5  3.5

# In this specic example we need >= the difference betwen the two max
nice_reverse(nd, 
             max = max.petal, 
             min = max(nd) - max.petal) |> 
  range()
#> [1] 0 4
```

<sup>Created on 2022-12-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Furthermore, I could not find where in `bestNormalize` you deal with negative values with `log_x`. Like how do you decide to exclude as a transformation method in the presence of negative values?

Edit: actually, I think it is adding the constant automatically on lines 55-57 of `log_x` in the following bit:

```r
min_a <- max(0, -(min(x, na.rm = TRUE) - eps))
  if(!length(a)) 
    a <- min_a
```

Perhaps if we readd this constant chunk after the first reversal but before the log, it would solve our problem?

**Comment by petersonR** [comment]
I think you are right that if we use the `min_a` part from the `log_x` transformation that could be a good solution. It might not fully prevent problems, but you could at least set `a` (or `eps`) to something large enough to handle new data outside the range decently well.

**Comment by rempsyc** [comment]
Almost everything is fixed now:

``` r
#   ____________________________________________________________________________
#   STEP 1: PREDICT CORRECTLY (SUCCESSFUL)                                  ####

devtools::load_all("D:/github/forks/bestNormalize")
#> ℹ Loading bestNormalize

# Create original data
set.seed(42)
x <- rgamma(1000, 1, 2)
x <- nice_reverse(x, max = 5, min = 4)
hist(x)
```



``` r

# Create double reverse object
object <- double_reverse_log(x)
hist(object$x.t)
```



``` r
object
#> Standardized double reversed Log_b(x + a) Transformation with 1000 nonmissing obs.:
#>  Relevant statistics:
#>  - a = 0 
#>  - b = 10 
#>  - mean (before standardization) = 9.585969 
#>  - sd (before standardization) = 0.5505899

# check transformed data from prediction
hist(predict(object))
```



``` r

# The orignal data is the same
expect_equal(object$x, x)

# The transformed data too :)
expect_equal(object$x.t, predict(object), check.attributes = FALSE)

#   ____________________________________________________________________________
#   STEP 2: INVERSE CORRECTLY (SUCCESSFUL)                                  ####

# Correct!
expect_equal(object$x, predict(object, inverse = TRUE))

hist(object$x)
```



``` r

hist(predict(object, inverse = TRUE))
```



``` r
# Correct inverse :)

#   ____________________________________________________________________________
#   STEP 3: INVERSE NEW DATA                                                ####

# That works (there are no NAs...)
nd <- seq(0, 4, length = 100)
pred <- predict(object, newdata = nd)
expect_true(!any(is.na(pred)))

# The inverse translation on new data gives back the original, unaltered data :)
nd2 <- predict(object, newdata = pred, inverse = TRUE)
expect_equal(nd, nd2)
```

<sup>Created on 2022-12-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rempsyc** [comment]
The last two failing tests are shown below. I am struggling to find the source of the bug in these cases but perhaps you will be able to figure this part out more easily than me.

``` r
devtools::load_all("D:/github/forks/bestNormalize")
#> ℹ Loading bestNormalize
library(usethis)
iris <- iris[1:30,]
train <- iris$Petal.Width
cl <- parallel::makeCluster(2)

# cluster and loo work well individually
expect_silent(bestNormalize(train, warn = FALSE, cluster = cl, quiet = TRUE))
expect_silent(bestNormalize(train, warn = FALSE, loo = TRUE, quiet = TRUE))

# but not together
expect_silent(bestNormalize(train, warn = FALSE, cluster = cl, loo = TRUE, quiet = TRUE))
#> Error in {: task 1 failed - "double_reverse_log  did not work;  Error in double_reverse_log(standardize = TRUE, warn = FALSE, x = c(0.2,  : 
#>   could not find function "double_reverse_log"
#> "
```

<sup>Created on 2022-12-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

What do you think it means, `could not find function "double_reverse_log"`?

It comes from the `get_loo_estimates` function. I've tried the following but cannot get it to work:

```r
> norm_stat_fn <- function(x) {
+   val <- nortest::pearson.test(x)
+   unname(val$stat/val$df)
+ }
> 
> method_names <- list("double_reverse_log")
> new_transforms <- method_names
> names(args) <- method_names
> 
> get_loo_estimates(
+   x = train, standardize = TRUE, norm_methods = method_names, cluster = cl, quiet = TRUE, 
+   warn = FALSE, args = args, new_transforms = NULL, norm_stat_fn = norm_stat_fn)
Error in { : 
  task 1 failed - "double_reverse_log  did not work;  Error in double_reverse_log(standardize = TRUE, warn = FALSE, x = c(0.2,  : 
  could not find function "double_reverse_log"
```

**Comment by petersonR** [comment]
Strange, the most recent version you pushed does pass all testing on my machine, after running `devtools::install()` locally. Maybe restart everything, do a fresh install, restart again, and re-run `devtools::test()`? 

I'm still seeing different results in the test below: 

```r
set.seed(1)
x1 <- 100- rgamma(100, .1)

drl_x1_obj <- double_reverse_log(x1)
all.equal(predict(drl_x1_obj, newdata = x1), predict(drl_x1_obj, x1))
[1] TRUE
 all.equal(predict(drl_x1_obj, newdata = x1[2]), predict(drl_x1_obj, x1)[2], check.attributes = FALSE)
[1] "Mean relative difference: 1.183229"
```

It looks like there's still a re-training step happening in `predict` as the culprit. I think values outside the range of min_x-eps and max_x + eps fed into `predict` need to come back as NA. Normally this is bad but it's how other functions in the package handle this kind of extrapolation, e.g. for `log_x`:   

```r
set.seed(123)
x2 <- rgamma(100, .1)
l_obj <- log_x(x2)

predict(l_obj, newdata = -.24)
[1] NaN
Warning message:
In log(newdata + object$a, object$b) : NaNs produced
```

I believe I can fix this by using `eps` as a "padding" for data outside the range of x. I'm going to merge this into a new branch on my side, fix there, and then merge the new branch to master from there. Thanks again for helping out, I'll ping you to test out in a little while.

**Comment by rempsyc** [comment]
Whoops, yup, I was working from the branch, but maybe I messed up in the beginning by switching branch after the first push? I can't remember. What does it say now on the new branch?

**Comment by petersonR** [comment]
Pulling into bestNormalize new branch, will add a few fixes there in a bit.

**Comment by rempsyc** [comment]
> Strange, the most recent version you pushed does pass all testing on my machine, after running devtools::install() locally. Maybe restart everything, do a fresh install, restart again, and re-run devtools::test()?

You were right! After formally installing the package, all tests work now. Strange indeed.

> I'm still seeing different results in the test below:

Whoopsie, forgot about this little one. Seems like you were able to fix it with your latest changes! 🥳 Good teamwork 😛

**Pull request merged**
